### PR TITLE
Fix static char array issues

### LINKED ISSUE #17: Compilation fails when static initialized char arrays are deserialized
We have `N` instead of `length`

https://github.com/bosagora/serialization/blob/1cb6c19d4b51b82e40438c08d27cdcfc9e487ca7/source/agora/serialization/Serializer.d#L609

### LINKED ISSUE #18: Default initialized static char arrays throw exception during deserialization
Character types initialized with all bits set by default; i.e. `char.init = ff`
During deserialization of these types in static arrays, UTF validation check happens; which results in throwing exception.

https://github.com/bosagora/serialization/blob/1cb6c19d4b51b82e40438c08d27cdcfc9e487ca7/source/agora/serialization/Serializer.d#L610

### PR DESCRIPTION
**Pull request by mkykadir**
See each commit

Fixes #17 and Fixes #18

### CODE REVIEW

**Comment by omerfirmak** [comment]
Needs test, see testSymmetry

**Comment by mkykadir** [comment]
> Needs test, see testSymmetry

Added and saw that uninitialized `char` arrays are not handled properly, since `char.init` is `FF` it doesn't validate.

**Comment by Geod24** [comment]
I don't know if we should `validate` `char[N]` TBF. An argument could be made that one should be able to set only one char in the array and it should be valid, which means any validation is impossible.

**Comment by mkykadir** [comment]
Ready to review with requested changes

**Review by linked0 — APPROVED** [review]
LGTM

**Pull request merged**
